Pending requests interlibrary loan
mlibrary/my_account pull request #106
Opened 2021-05-04 18:18 UTC by erinesullivan

# Overview
This pull request makes `Pending Requests > Interlibrary Loan` display items based on if the user has items where the `TransactionStatus` contains any of these words (according to [ILLiad Default Statuses & Queues](https://support.atlas-sys.com/hc/en-us/articles/360011812114-ILLiad-Default-Statuses-Queues) and personal testing):
- "Awaiting"
- "In Transit"
- "Pending"
- "Queue"
- "Request Sent"
- "Searching"
- "Submitted"

## Cancel Link
A `Cancel Request` link has been added, which links to `https://ill.lib.umich.edu/illiad/illiad.dll?Action=21&Type=10&Value=<%=interlibrary_loan_request.illiad_id%>`.

## Title Hierarchy
The order of the title hierarchy has changed. When testing on my personal account (`esulliv`), it was showing the book chapter number as the title, and not the book title itself.

## Unit Tests
Unit tests have been added/broken up to help match the added classes.

## Testing
- Run the tests to make sure they pass: `docker-compose run web bundle exec rspec`
- Break the tests to double-check that they work
- In `./models/items/interlibrary_loan/interlibrary_loan_requests.rb` on `line 4` in the `actions` array, add the word `"Finished"`. Save and `docker-compose restart`. You should see about four items display.

2021-05-05 14:43 UTC, niquerio requested changes
Looking good. Just some small changes.

2021-05-05 14:43 UTC, niquerio commented on spec/models/items/interlibrary_loan/interlibrary_loan_requests_spec.rb
>  end
I'd make sure these tests still work for one loan or one request. I'd load illiad_request.json into a variable in before(:each), explicitly modify the transaction type to match. Then load it in the stub.

2021-05-05 14:43 UTC, niquerio commented on views/interlibrary_loan_requests.erb
> +      <p>Showing <strong><%= interlibrary_loan_requests.count %></strong> <%= interlibrary_loan_requests.count == 1 ? "item" : "items" %></p>
This should a method in `models/items/items.rb`. maybe:
```
def item_text
  count ==1 ? "item" : "items"
end
```
And then write a corresponding test. (Which is easier to do in the model than for the view)

2021-05-05 14:43 UTC, niquerio commented on views/interlibrary_loan_requests.erb
> +          <a href="https://ill.lib.umich.edu/illiad/illiad.dll?Action=21&Type=10&Value=<%=interlibrary_loan_request.illiad_id%>">Cancel Request</a>
You could make the url a method in the request model, and a corresponding one in the loan model.

2021-05-05 14:43 UTC, niquerio commented on views/interlibrary_loans.erb
> +            <a href="https://ill.lib.umich.edu/illiad/illiad.dll?Action=11&Form=71&Value=<%=interlibrary_loan.illiad_id%>">Request Renewal</a>
See above. Making a url method in the loan model would make sense here.

2021-05-06 13:18 UTC, erinesullivan commented on spec/models/items/interlibrary_loan/interlibrary_loan_requests_spec.rb
> +  context "one request" do
```suggestion
  context "two requests" do
```

2021-05-10 17:17 UTC, niquerio approved these changes

2021-05-10 17:18 UTC, merged